// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RegistrosAPI.Models;

public partial class Datos
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public string ContactoPersona { get; set; }

    public bool AceptoLosTerminos { get; set; }
}