// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RegistrosAPI.Models;

public partial class FormulariosDBContext : DbContext
{
    public FormulariosDBContext(DbContextOptions<FormulariosDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Datos> Datos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Datos>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Datos__3214EC07D5ED0FA5");

            entity.Property(e => e.ContactoPersona)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}